import { ImageSourcePropType } from 'react-native';

export const defaultCountryPhoto = require('../assets/images/BackHome.png');

const countryPhotoRegistry: Record<string, ImageSourcePropType> = {
    // Europe
    albania: require('../assets/country-photos/Albania.jpg'),
    andorra: require('../assets/country-photos/Andorra.jpg'),
    armenia: require('../assets/country-photos/Armenia.jpg'),
    austria: require('../assets/country-photos/Austria.jpg'),
    azerbaijan: require('../assets/country-photos/Azerbaijan.jpg'),
    belarus: require('../assets/country-photos/Belarus.jpg'),
    belgium: require('../assets/country-photos/Belgium.jpg'),
    bosnia: require('../assets/country-photos/Bosnia.jpg'),
    'bosnia-and-herzegovina': require('../assets/country-photos/Bosnia.jpg'),
    bulgaria: require('../assets/country-photos/Bulgaria.jpg'),
    croatia: require('../assets/country-photos/Croatia.jpg'),
    cyprus: require('../assets/country-photos/Cyprus.jpg'),
    czechia: require('../assets/country-photos/Czech-Republic.jpg'),
    'czech-republic': require('../assets/country-photos/Czech-Republic.jpg'),
    denmark: require('../assets/country-photos/Denmark.jpg'),
    estonia: require('../assets/country-photos/Estonia.jpg'),
    finland: require('../assets/country-photos/Finland.jpg'),
    france: require('../assets/country-photos/France.jpg'),
    georgia: require('../assets/country-photos/Georgia.jpg'),
    germany: require('../assets/country-photos/Germany.jpg'),
    greece: require('../assets/country-photos/Greece.jpg'),
    hungary: require('../assets/country-photos/Hungary.jpg'),
    iceland: require('../assets/country-photos/Iceland.jpg'),
    ireland: require('../assets/country-photos/Ireland.jpg'),
    israel: require('../assets/country-photos/Israel.jpg'),
    italy: require('../assets/country-photos/Italy.jpg'),
    japan: require('../assets/country-photos/Japan.jpg'),
    indonesia: require('../assets/country-photos/Indonesia.jpg'),
    philippines: require('../assets/country-photos/Philippines.jpg'),
    'south-korea': require('../assets/country-photos/South-Korea.jpg'),
    korea: require('../assets/country-photos/South-Korea.jpg'),
    'republic-of-korea': require('../assets/country-photos/South-Korea.jpg'),
    thailand: require('../assets/country-photos/Thailand.jpg'),
    vietnam: require('../assets/country-photos/Vietnam.jpg'),
    australia: require('../assets/country-photos/Australia.jpg'),
    kazakhstan: require('../assets/country-photos/Kazakhstan.jpg'),
    kosovo: require('../assets/country-photos/Kosovo.jpg'),
    latvia: require('../assets/country-photos/Latvia.jpg'),
    liechtenstein: require('../assets/country-photos/Liechtenstein.jpg'),
    lithuania: require('../assets/country-photos/Lithuania.jpg'),
    luxembourg: require('../assets/country-photos/Luxembourg.jpg'),
    malta: require('../assets/country-photos/Malta.jpg'),
    moldova: require('../assets/country-photos/Moldova.jpg'),
    monaco: require('../assets/country-photos/Monaco.jpg'),
    montenegro: require('../assets/country-photos/Montenegro.jpg'),
    netherlands: require('../assets/country-photos/Netherlands.jpg'),
    'the-netherlands': require('../assets/country-photos/Netherlands.jpg'),
    norway: require('../assets/country-photos/Norway.jpg'),
    poland: require('../assets/country-photos/Poland.jpg'),
    portugal: require('../assets/country-photos/Portugal.jpg'),
    romania: require('../assets/country-photos/Romania.jpg'),
    'san-marino': require('../assets/country-photos/San-Marino.jpg'),
    serbia: require('../assets/country-photos/Serbia.jpg'),
    slovakia: require('../assets/country-photos/Slovakia.jpg'),
    slovenia: require('../assets/country-photos/Slovenia.jpg'),
    spain: require('../assets/country-photos/Spain.jpg'),
    sweden: require('../assets/country-photos/Sweden.jpg'),
    switzerland: require('../assets/country-photos/Switzerland.jpg'),
    turkey: require('../assets/country-photos/Turkey.jpg'),
    ukraine: require('../assets/country-photos/Ukraine.jpg'),
    'united-kingdom': require('../assets/country-photos/United-Kingdom.jpg'),
    'vatican-city': require('../assets/country-photos/Vatican-City.jpg'),

    // United States (folder name = state; also 2-letter aliases)
    alabama: require('../assets/country-photos/Alabama.jpg'),
    al: require('../assets/country-photos/Alabama.jpg'),
    alaska: require('../assets/country-photos/Alaska.jpg'),
    ak: require('../assets/country-photos/Alaska.jpg'),
    arizona: require('../assets/country-photos/Arizona.jpg'),
    az: require('../assets/country-photos/Arizona.jpg'),
    arkansas: require('../assets/country-photos/Arkansas.jpg'),
    ar: require('../assets/country-photos/Arkansas.jpg'),
    california: require('../assets/country-photos/California.jpg'),
    ca: require('../assets/country-photos/California.jpg'),
    colorado: require('../assets/country-photos/Colorado.jpg'),
    co: require('../assets/country-photos/Colorado.jpg'),
    connecticut: require('../assets/country-photos/Connecticut.jpg'),
    ct: require('../assets/country-photos/Connecticut.jpg'),
    delaware: require('../assets/country-photos/Delaware.jpg'),
    de: require('../assets/country-photos/Delaware.jpg'),
    florida: require('../assets/country-photos/Florida.jpg'),
    fl: require('../assets/country-photos/Florida.jpg'),
    hawaii: require('../assets/country-photos/Hawaii.jpg'),
    hi: require('../assets/country-photos/Hawaii.jpg'),
    idaho: require('../assets/country-photos/Idaho.jpg'),
    id: require('../assets/country-photos/Idaho.jpg'),
    illinois: require('../assets/country-photos/Illinois.jpg'),
    il: require('../assets/country-photos/Illinois.jpg'),
    indiana: require('../assets/country-photos/Indiana.jpg'),
    in: require('../assets/country-photos/Indiana.jpg'),
    iowa: require('../assets/country-photos/Iowa.jpg'),
    ia: require('../assets/country-photos/Iowa.jpg'),
    kansas: require('../assets/country-photos/Kansas.jpg'),
    ks: require('../assets/country-photos/Kansas.jpg'),
    kentucky: require('../assets/country-photos/Kentucky.jpg'),
    ky: require('../assets/country-photos/Kentucky.jpg'),
    louisiana: require('../assets/country-photos/Louisiana.jpg'),
    la: require('../assets/country-photos/Louisiana.jpg'),
    maine: require('../assets/country-photos/Maine.jpg'),
    me: require('../assets/country-photos/Maine.jpg'),
    maryland: require('../assets/country-photos/Maryland.jpg'),
    md: require('../assets/country-photos/Maryland.jpg'),
    massachusetts: require('../assets/country-photos/Massachusetts.jpg'),
    ma: require('../assets/country-photos/Massachusetts.jpg'),
    michigan: require('../assets/country-photos/Michigan.jpg'),
    mi: require('../assets/country-photos/Michigan.jpg'),
    minnesota: require('../assets/country-photos/Minnesota.jpg'),
    mn: require('../assets/country-photos/Minnesota.jpg'),
    mississippi: require('../assets/country-photos/Mississippi.jpg'),
    ms: require('../assets/country-photos/Mississippi.jpg'),
    missouri: require('../assets/country-photos/Missouri.jpg'),
    mo: require('../assets/country-photos/Missouri.jpg'),
    montana: require('../assets/country-photos/Montana.jpg'),
    mt: require('../assets/country-photos/Montana.jpg'),
    nebraska: require('../assets/country-photos/Nebraska.jpg'),
    ne: require('../assets/country-photos/Nebraska.jpg'),
    nevada: require('../assets/country-photos/Nevada.jpg'),
    nv: require('../assets/country-photos/Nevada.jpg'),
    'new-hampshire': require('../assets/country-photos/New-Hampshire.jpg'),
    nh: require('../assets/country-photos/New-Hampshire.jpg'),
    'new-jersey': require('../assets/country-photos/New-Jersey.jpg'),
    nj: require('../assets/country-photos/New-Jersey.jpg'),
    'new-mexico': require('../assets/country-photos/New-Mexico.jpg'),
    nm: require('../assets/country-photos/New-Mexico.jpg'),
    'new-york': require('../assets/country-photos/New-York.jpg'),
    ny: require('../assets/country-photos/New-York.jpg'),
    'north-carolina': require('../assets/country-photos/North-Carolina.jpg'),
    nc: require('../assets/country-photos/North-Carolina.jpg'),
    'north-dakota': require('../assets/country-photos/North-Dakota.jpg'),
    nd: require('../assets/country-photos/North-Dakota.jpg'),
    ohio: require('../assets/country-photos/Ohio.jpg'),
    oh: require('../assets/country-photos/Ohio.jpg'),
    oklahoma: require('../assets/country-photos/Oklahoma.jpg'),
    ok: require('../assets/country-photos/Oklahoma.jpg'),
    oregon: require('../assets/country-photos/Oregon.jpg'),
    or: require('../assets/country-photos/Oregon.jpg'),
    pennsylvania: require('../assets/country-photos/Pennsylvania.jpg'),
    pa: require('../assets/country-photos/Pennsylvania.jpg'),
    'rhode-island': require('../assets/country-photos/Rhode-Island.jpg'),
    ri: require('../assets/country-photos/Rhode-Island.jpg'),
    'south-carolina': require('../assets/country-photos/South-Carolina.jpg'),
    sc: require('../assets/country-photos/South-Carolina.jpg'),
    'south-dakota': require('../assets/country-photos/South-Dakota.jpg'),
    sd: require('../assets/country-photos/South-Dakota.jpg'),
    tennessee: require('../assets/country-photos/Tennessee.jpg'),
    tn: require('../assets/country-photos/Tennessee.jpg'),
    texas: require('../assets/country-photos/Texas.jpg'),
    tx: require('../assets/country-photos/Texas.jpg'),
    utah: require('../assets/country-photos/Utah.jpg'),
    ut: require('../assets/country-photos/Utah.jpg'),
    vermont: require('../assets/country-photos/Vermont.jpg'),
    vt: require('../assets/country-photos/Vermont.jpg'),
    virginia: require('../assets/country-photos/Virginia.jpg'),
    va: require('../assets/country-photos/Virginia.jpg'),
    washington: require('../assets/country-photos/Washington.jpg'),
    wa: require('../assets/country-photos/Washington.jpg'),
    'west-virginia': require('../assets/country-photos/West-Virginia.jpg'),
    wv: require('../assets/country-photos/West-Virginia.jpg'),
    wisconsin: require('../assets/country-photos/Wisconsin.jpg'),
    wi: require('../assets/country-photos/Wisconsin.jpg'),
    wyoming: require('../assets/country-photos/Wyoming.jpg'),
    wy: require('../assets/country-photos/Wyoming.jpg'),
    'district-of-columbia': require('../assets/country-photos/District-of-Columbia.jpg'),
    dc: require('../assets/country-photos/District-of-Columbia.jpg'),

    // North America
    canada: require('../assets/country-photos/Canada.jpg'),
    mexico: require('../assets/country-photos/Mexico.jpg'),

    // Central America
    belize: require('../assets/country-photos/Belize.jpg'),
    'costa-rica': require('../assets/country-photos/Costa-Rica.jpg'),
    'el-salvador': require('../assets/country-photos/El-Salvador.jpg'),
    guatemala: require('../assets/country-photos/Guatemala.jpg'),
    honduras: require('../assets/country-photos/Honduras.jpg'),
    nicaragua: require('../assets/country-photos/Nicaragua.jpg'),
    panama: require('../assets/country-photos/Panama.jpg'),

    // Caribbean
    bahamas: require('../assets/country-photos/Bahamas.jpg'),
    barbados: require('../assets/country-photos/Barbados.jpg'),
    cuba: require('../assets/country-photos/Cuba.jpg'),
    'dominican-republic': require('../assets/country-photos/Dominican-Republic.jpg'),
    haiti: require('../assets/country-photos/Haiti.jpg'),
    jamaica: require('../assets/country-photos/Jamaica.jpg'),
    'puerto-rico': require('../assets/country-photos/Puerto-Rico.jpg'),
    'trinidad-and-tobago': require('../assets/country-photos/Trinidad-and-Tobago.jpg'),

    // South America
    argentina: require('../assets/country-photos/Argentina.jpg'),
    bolivia: require('../assets/country-photos/Bolivia.jpg'),
    brazil: require('../assets/country-photos/Brazil.jpg'),
    brasil: require('../assets/country-photos/Brazil.jpg'),
    chile: require('../assets/country-photos/Chile.jpg'),
    colombia: require('../assets/country-photos/Colombia.jpg'),
    ecuador: require('../assets/country-photos/Ecuador.jpg'),
    'french-guiana': require('../assets/country-photos/French-Guiana.jpg'),
    guyana: require('../assets/country-photos/Guyana.jpg'),
    paraguay: require('../assets/country-photos/Paraguay.jpg'),
    peru: require('../assets/country-photos/Peru.jpg'),
    suriname: require('../assets/country-photos/Suriname.jpg'),
    uruguay: require('../assets/country-photos/Uruguay.jpg'),
    venezuela: require('../assets/country-photos/Venezuela.jpg'),
};

const normalizeCountryKey = (countryName: string) =>
    countryName
        .trim()
        .toLowerCase()
        .replace(/\s+/g, '-');

export const getCountryPhoto = (countryName: string): ImageSourcePropType =>
    countryPhotoRegistry[normalizeCountryKey(countryName)] ?? defaultCountryPhoto;

/** Basenames you still need to replace under assets/country-photos/ (new entries only). */
export const ADDED_COUNTRY_PHOTO_FILES = [
    'Alabama.jpg',
    'Alaska.jpg',
    'Arizona.jpg',
    'Arkansas.jpg',
    'Colorado.jpg',
    'Connecticut.jpg',
    'Delaware.jpg',
    'Hawaii.jpg',
    'Idaho.jpg',
    'Illinois.jpg',
    'Indiana.jpg',
    'Iowa.jpg',
    'Kansas.jpg',
    'Kentucky.jpg',
    'Louisiana.jpg',
    'Maine.jpg',
    'Maryland.jpg',
    'Massachusetts.jpg',
    'Michigan.jpg',
    'Minnesota.jpg',
    'Mississippi.jpg',
    'Missouri.jpg',
    'Montana.jpg',
    'Nebraska.jpg',
    'Nevada.jpg',
    'New-Hampshire.jpg',
    'New-Jersey.jpg',
    'New-Mexico.jpg',
    'North-Carolina.jpg',
    'North-Dakota.jpg',
    'Ohio.jpg',
    'Oklahoma.jpg',
    'Oregon.jpg',
    'Pennsylvania.jpg',
    'Rhode-Island.jpg',
    'South-Carolina.jpg',
    'South-Dakota.jpg',
    'Tennessee.jpg',
    'Texas.jpg',
    'Utah.jpg',
    'Vermont.jpg',
    'Washington.jpg',
    'West-Virginia.jpg',
    'Wisconsin.jpg',
    'Wyoming.jpg',
    'District-of-Columbia.jpg',
    'Canada.jpg',
    'Mexico.jpg',
    'Belize.jpg',
    'Costa-Rica.jpg',
    'El-Salvador.jpg',
    'Guatemala.jpg',
    'Honduras.jpg',
    'Nicaragua.jpg',
    'Panama.jpg',
    'Bahamas.jpg',
    'Barbados.jpg',
    'Cuba.jpg',
    'Dominican-Republic.jpg',
    'Haiti.jpg',
    'Jamaica.jpg',
    'Puerto-Rico.jpg',
    'Trinidad-and-Tobago.jpg',
    'Argentina.jpg',
    'Bolivia.jpg',
    'Brazil.jpg',
    'Chile.jpg',
    'Colombia.jpg',
    'Ecuador.jpg',
    'French-Guiana.jpg',
    'Guyana.jpg',
    'Paraguay.jpg',
    'Peru.jpg',
    'Suriname.jpg',
    'Uruguay.jpg',
    'Venezuela.jpg',
    'Indonesia.jpg',
    'Philippines.jpg',
    'South-Korea.jpg',
    'Thailand.jpg',
    'Vietnam.jpg',
    'Australia.jpg',
] as const;
